version: '3.7'

networks:
    familyconnect:

services:
  family-connect-dev:
    container_name: family-connect-dev
    networks:
      - familyconnect
    volumes:
      - ./:/workspaces/family-connect
      - /home/node/.npm
      - /workspaces/node_modules
  neo4j:
    container_name: neo4jlocal
    networks:
      - familyconnect
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"