version: '3.7'
services:
  family-connect-dev:
    volumes:
      - ./:/workspaces/family-connect
      - /home/node/.npm
      - /workspaces/node_modules
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
    depends_on:
      - dynamodb-local